# Generated by Django 4.1.3 on 2023-02-18 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Emp_id", models.IntegerField()),
                ("Name", models.CharField(max_length=200, null=True)),
                ("Mobile", models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("depart_id", models.IntegerField()),
                (
                    "depart_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tests.employee"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Coursenotes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_dtl", models.CharField(max_length=200)),
                (
                    "coursename",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tests.department",
                    ),
                ),
            ],
        ),
    ]
